services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www/laravel
  php:
    build:
      context: dockerfiles
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/laravel

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: posgres_db
      POSTGRES_USER: posgres_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - "./data/db/pgsql:/var/lib/pgsql"
